version: '3'

tasks:
  test:
    cmds:
      - ./scripts/test.sh
  build:
    dotenv:
      - './.env'
    cmds:
      - GITHUB_SHA="$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 6 | head -n 1)" ./scripts/publish.sh

  setup:
    desc: 'Setup the repository'
    cmds: #
      - echo "Completed"
      #
      #
  lint:
    desc: Lints the whole code-base
    cmds:
      - pre-commit run --all
  #
