version: '3'

vars:
  PLATFORM: sulfone
  SERVICE: helium

tasks:
  build:
    dotenv:
      - './.env'
    cmds:
      - GITHUB_SHA="$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 6 | head -n 1)" ./scripts/publish.sh
