name: CD

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  cyanprint:
    name: Build and Push
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/⚡reusable-cyanprint.yaml
    secrets: inherit
    with:
      atomi_platform: ketone
      atomi_service: new-cyanprint
      version: ${{ github.ref_name }}
