name: CI

on:
  push:

jobs:
  precommit:
    name: Pre-Commit
    uses: ./.github/workflows/⚡reusable-precommit.yaml
    secrets: inherit
    with:
      atomi_platform: ketone
      atomi_service: new-cyanprint
  test:
    name: Test
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-ketone-new-cyanprint-nix-store-cache
    env:
      DOMAIN: ghcr.io
      GITHUB_REPO_REF: ${{ github.repository }}
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_BRANCH: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: AtomiCloud/actions.setup-nix@v2
      - name: Run CyanPrint Tests
        run: |
          GITHUB_REPO_REF="$(echo "${GITHUB_REPO_REF}" | tr '[:upper:]' '[:lower:]')"
          export GITHUB_REPO_REF
          nix develop .#ci -c cyanprint --version
          nix develop .#ci -c cyanprint test template .
  #
  docker:
    name: Build Docker - ${{ matrix.image_name }}
    needs: test
    strategy:
      matrix:
        include:
          - context: ./cyan
            dockerfile: ./cyan/Dockerfile
            image_name: template-template
          - context: ./cyan
            dockerfile: ./cyan/blob.Dockerfile
            image_name: template-blob
    uses: ./.github/workflows/⚡reusable-docker.yaml
    secrets: inherit
    with:
      atomi_platform: ketone
      atomi_service: new-cyanprint

      context: ${{ matrix.context }}
      dockerfile: ${{ matrix.dockerfile }}
      image_name: ${{ matrix.image_name }}
  #
  #
