name: CI

on:
  push:

jobs:
  precommit:
    name: Pre-Commit
    uses: ./.github/workflows/⚡reusable-precommit.yaml
    secrets: inherit
    with:
      atomi_platform: ketone
      atomi_service: new-cyanprint
  docker:
    name: Docker Build
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-ketone-new-cyanprint-nix-store-cache
    steps:
      - uses: actions/checkout@v4
      - uses: AtomiCloud/actions.setup-nix@v2
      - uses: rlespinasse/github-slug-action@v3.x
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Images
        env:
          DOMAIN: ghcr.io
          GITHUB_REPO_REF: ${{ github.repository }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USER: ${{ github.actor }}
        run: |
          GITHUB_REPO_REF="$(echo "${GITHUB_REPO_REF}" | tr '[:upper:]' '[:lower:]')"
          export GITHUB_REPO_REF
          BRANCH="${GITHUB_REF_SLUG//[._-]*$//}"
          IMAGE_VERSION="${GITHUB_SHA:0:6}-${BRANCH}"
          nix develop .#ci -c cyanprint build "${IMAGE_VERSION}"
